#!/usr/bin/env bash

set -e

client_key=$(cat ./ansible/keys/wireguard_client)
server_pubkey=$(cat ./ansible/keys/wireguard.pub)
output_name="gateway_public_ip"
gateway_ip=$(terraform -chdir=./terraform output -raw $output_name)

cat <<END
[Interface]
PrivateKey = $client_key
Address = 10.10.0.1/32
DNS = 10.10.0.0

[Peer]
PublicKey = $server_pubkey
AllowedIPs = 10.10.0.0/24, 10.0.0.0/16
Endpoint = $gateway_ip:51820
END